lane :release do
  api_key = app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
    key_content: ENV['APP_STORE_CONNECT_API_KEY"']
  )

  match(      
    type: 'appstore', 
    app_identifier: ["com.test.todo.kehinde"],
    api_key: api_key,
    readonly: true
  )
  ...
end
