default_platform(:ios)

platform :ios do
  lane :upload_ipa_to_testflight_app_store_connect do
    # Fetch App Store Connect API Key
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: File.read(ENV['APP_STORE_CONNECT_API_KEY'])
    )

    # Get the latest build number from TestFlight
    latest_build = latest_testflight_build_number(
      app_identifier: "com.test.todo.kehinde",  # Replace with your app's identifier
      api_key: api_key,
      version: "1.0"  # Specify your app version
    )

    UI.message("Latest build number: #{latest_build}")

    # Upload the IPA to TestFlight
    pilot(
      ipa: "/Users/runner/work/_temp/latest-Todo.ipa",  # Path to your IPA file
      app_identifier: "com.test.todo.kehinde",  # Replace with your app's identifier
      api_key: api_key,  # Pass the API key
      skip_waiting_for_build_processing: true  # Skip waiting for build processing in TestFlight
    )
  end
end
