default_platform(:ios)

platform :ios do
  desc "Upload IPA to TestFlight"
  lane :upload_ipa_to_testflight do
    # Load the API Key from the generated json file
    api_key_path = File.join(ENV['RUNNER_TEMP'], "api_key.json")  # Assuming RUNNER_TEMP is the directory where the file is placed
    api_key = app_store_connect_api_key(path: api_key_path)

    # Use pilot to upload the IPA to TestFlight
    pilot(
      api_key: api_key,
      ipa: "#{ENV['RUNNER_TEMP']}/ToDo.ipa",  # Ensure the path is correctly concatenated
      app_identifier: "com.test.todo.kehinde" # Ensure this matches exactly
    )
  end
end
