name: "Deploy iOS app"

on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      # Initial setup for the job
      - name: Set up job
        run: echo "Setting up job..."

      # Enable debug logging
      - name: Set debug logging
        run: echo "##[debug]Logging enabled"

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Ruby and Fastlane
      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      # Download the IPA file from S3
      - name: List and Download the Latest IPA from S3
        run: |
          LATEST_IPA=$(aws s3api list-objects-v2 --bucket ${{ secrets.AWS_S3_BUCKET }} --prefix ipa/ --query 'sort_by(Contents, &LastModified)[-1].Key' --output text)
          echo "Latest IPA: $LATEST_IPA"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/${LATEST_IPA} $RUNNER_TEMP/latest-Todo.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Upload IPA to TestFlight using Fastlane
      - name: Upload IPA to TestFlight using Fastlane
        run: bundle exec fastlane upload_ipa_to_testflight
        env:
         FASTLANE_APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}  # Ensure this name matches what you use in your Fastfile

      # Final step to indicate job completion
      - name: Complete job
        run: echo "Job complete"       