name: Deploy iOS app

on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you are using with Fastlane

      - name: Install Bundler and Fastlane Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set Up Environment Variables
        run: |
          echo "APP_STORE_CONNECT_API_KEY=$APP_STORE_CONNECT_API_KEY" >> $GITHUB_ENV
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: List and Download the Latest IPA from S3
        run: |
          LATEST_IPA=$(aws s3api list-objects-v2 --bucket ${{ secrets.AWS_S3_BUCKET }} --prefix ipa/ --query 'sort_by(Contents, &LastModified)[-1].Key' --output text)
          echo "Latest IPA: $LATEST_IPA"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/${LATEST_IPA} $RUNNER_TEMP/latest-Todo.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Upload IPA to TestFlight using Fastlane
        run: bundle exec fastlane upload_ipa_to_testflight
        env:
          FASTLANE_APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY  # Ensure this name matches what you use in your Fastfile

      - name: Complete Job
        run: echo "Job complete"
