name: "Deploy iOS app"
on:
  workflow_run:
    workflows: ["Build iOS app"]
    types:
      - completed

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Set up job
        run: echo "Setting up job..."

      - name: Set debug logging
        run: |
          echo "##[debug]Logging enabled"
          echo "##[debug]Environment Variables:"
          echo "APP_STORE_CONNECT_API_KEY_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}"
          echo "APP_STORE_CONNECT_API_KEY_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}"
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler gems
        run: bundle install

      - name: Decode API Key File
        run: |
          echo "##[debug]Decoding API Key"
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}" | base64 --decode > ${{ runner.temp }}/api_key.json
        shell: bash

      - name: List and Download the Latest IPA from S3
        run: |
          echo "##[debug]Fetching the latest IPA from S3"
          LATEST_IPA=$(aws s3api list-objects-v2 --bucket ${{ secrets.AWS_S3_BUCKET }} --prefix ipa/ --query 'sort_by(Contents, &LastModified)[-1].Key' --output text)
          echo "Latest IPA: $LATEST_IPA"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/${LATEST_IPA} ${{ runner.temp }}/latest-Todo.ipa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Check IPA File Presence
        run: |
          echo "##[debug]Verifying IPA file presence"
          ls -l ${{ runner.temp }}
          if [ -f "${{ runner.temp }}/latest-Todo.ipa" ]; then
            echo "IPA file is ready for upload."
          else
            echo "IPA file not found, aborting."
            exit 1
          fi

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ runner.temp }}/api_key.json
        run: |
          echo "##[debug]Uploading IPA to TestFlight"
          bundle exec fastlane upload_ipa_to_testflight

      - name: Cleanup API Key File
        if: always()
        run: |
          echo "##[debug]Cleaning up API Key file"
          rm -f ${{ runner.temp }}/api_key.json

      - name: List Project Directory (Debug)
        run: |
          echo "##[debug]Listing project directory"
          pwd
          ls -la
          ls -la ToDo/
          ls -la ToDo.xcodeproj/
          ls -la ToDo.xcodeproj/project.pbxproj